### ISSUE TITLE
Shoulder angle should be in natural units

### ISSUE THREAD

**Issue by jakebruce** [RAWrobotics/Orion5#2]
It looks like the API requires the shoulder angle to be multiplied by the gear ratio of 2.857. This should definitely be handled under the hood, so users don't have to know anything about the arbitrary inner workings of the system.

**Comment by linzwatt** [comment]
Thanks for this, I'll include it in the next public commit (we develop on a private repo). We're working on tidying up and expanding the API, until recently we had only users from one educational institution, so we designed the MATLAB API around their use case. Now we need to focus more on the python library for general use

**Comment by linzwatt** [comment]
@jakebruce the shoulder angle is now handled inside the latest version of Python libraries, which are now available via pip: https://pypi.org/project/rawrobotics-orion5/
